// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORM.EF;

namespace ORM.EF.Migrations
{
    [DbContext(typeof(CourseWorkContext))]
    [Migration("20211122105718_changeProp1")]
    partial class changeProp1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("ORM.EF.Entities.CourseWorkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MentorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.ToTable("CourseWorks");
                });

            modelBuilder.Entity("ORM.EF.Entities.MentorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("ORM.EF.Entities.StudentEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ORM.EF.Entities.CourseWorkEntity", b =>
                {
                    b.HasOne("ORM.EF.Entities.MentorEntity", "Mentor")
                        .WithMany("CourseWorks")
                        .HasForeignKey("MentorId");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("ORM.EF.Entities.StudentEntity", b =>
                {
                    b.HasOne("ORM.EF.Entities.CourseWorkEntity", "CourseWork")
                        .WithOne("Student")
                        .HasForeignKey("ORM.EF.Entities.StudentEntity", "Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("CourseWork");
                });

            modelBuilder.Entity("ORM.EF.Entities.CourseWorkEntity", b =>
                {
                    b.Navigation("Student");
                });

            modelBuilder.Entity("ORM.EF.Entities.MentorEntity", b =>
                {
                    b.Navigation("CourseWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
